import type { Category } from "./types";

/**
 * English concept-id → Food Icon Pack slug, for the "foodiconpack" icon style.
 * Values are `"<category>/<slug>"` paths under `public/icons/foodiconpack/`
 * (SVG, free CC BY 4.0 "Common ingredient icons" / "Common Beverages" packs
 * from foodiconpack.com). Keys only need to be English: a non-English item
 * name is resolved to its English concept id in `categorizeIngredient()`
 * (`src/lib/data.ts` concept `aliases`) before it ever becomes an `iconKey`,
 * so this map — like `foodEmoji` in `FoodIcon.tsx` — never needs per-language
 * entries. Only ~245 of the concept ids used in `FoodIcon.tsx` have a
 * free-pack equivalent — dishes/snacks/baked goods mostly don't. When a
 * concept is missing, `FoodIcon` falls back to `foodiconpackCategoryFallback`
 * below — never to the emoji glyph, so the outline style stays visually
 * consistent. Built by matching `FoodIcon.tsx`'s `foodEmoji` keys against the
 * pack's slug lists, with a handful of hand-picked fixes where an
 * emoji-sharing key borrowed a mismatched icon.
 */
export const foodiconpackIndex: Record<string, string> = {
  "almond-milk": "beverages/almond_milk",
  "almonds": "ingredients/almonds",
  "anchovies": "ingredients/anchovy",
  "apple": "ingredients/apple",
  "apple-juice": "beverages/apple_juice",
  "artichoke": "ingredients/artichoke",
  "asparagus": "ingredients/asparagus",
  "aubergine": "ingredients/eggplant",
  "avocado": "ingredients/avocado",
  "bacon": "ingredients/bacon",
  "baking-powder": "ingredients/baking_powder",
  "baking-soda": "ingredients/baking_soda",
  "balsamic-vinegar": "ingredients/balsamic_vinegar",
  "banana": "ingredients/banana",
  "basil": "ingredients/basil",
  "bay-leaf": "ingredients/bay_leaf",
  "beans": "ingredients/chickpeas",
  "beef": "ingredients/beef",
  "beer": "ingredients/beer",
  "bell-pepper": "ingredients/bell_pepper",
  "berries": "ingredients/berries",
  "black-pepper": "ingredients/black_pepper",
  "blackberries": "ingredients/blackberry",
  "blueberries": "ingredients/blueberry",
  "bouillon": "ingredients/chicken_broth",
  "brie": "ingredients/brie",
  "broccoli": "ingredients/broccoli",
  "broth": "ingredients/chicken_broth",
  "brown-sugar": "ingredients/brown_sugar",
  "brownie": "ingredients/cocoa_powder",
  "butter": "ingredients/butter",
  "cabbage": "ingredients/cabbage",
  "capers": "ingredients/capers",
  "cappuccino": "beverages/cappuccino",
  "carrot": "ingredients/carrot",
  "carrots": "ingredients/carrot",
  "cashews": "ingredients/cashews",
  "cauliflower": "ingredients/cauliflower",
  "celery": "ingredients/celery",
  "cereal": "ingredients/baking_powder",
  "champagne": "beverages/champagne",
  "cheddar": "ingredients/cheddar",
  "cheese": "ingredients/brie",
  "cherries": "ingredients/cherry",
  "chicken": "ingredients/chicken",
  "chickpeas": "ingredients/chickpeas",
  "chili": "ingredients/chili_pepper",
  "chili-flakes": "ingredients/chili_pepper",
  "chocolate": "ingredients/cocoa_powder",
  "chocolate-bar": "ingredients/cocoa_powder",
  "chocolate-spread": "ingredients/cocoa_powder",
  "cider": "beverages/cider",
  "cilantro": "ingredients/cilantro",
  "cinnamon": "ingredients/cinnamon",
  "clams": "ingredients/clams",
  "cocoa": "ingredients/cocoa_powder",
  "cocoa-powder": "ingredients/cocoa_powder",
  "coconut": "ingredients/coconut",
  "coconut-milk": "ingredients/coconut_milk",
  "cod": "ingredients/cod",
  "coffee": "ingredients/coffee",
  "cola": "beverages/coca_cola",
  "corn": "ingredients/corn",
  "cottage-cheese": "ingredients/cottage_cheese",
  "courgette": "ingredients/cucumber",
  "couscous": "ingredients/couscous",
  "crab": "ingredients/crab",
  "cream": "ingredients/cream",
  "cream-cheese": "ingredients/cream_cheese",
  "cucumber": "ingredients/cucumber",
  "cumin": "ingredients/sesame_seeds",
  "curry-powder": "ingredients/curry_powder",
  "dates": "ingredients/date",
  "duck": "ingredients/duck",
  "eggplant": "ingredients/eggplant",
  "eggs": "ingredients/eggs",
  "energy-drink": "beverages/energy_drink",
  "espresso": "ingredients/espresso",
  "feta": "ingredients/feta",
  "fish": "ingredients/anchovy",
  "fish-sauce": "ingredients/fish_sauce",
  "flour": "ingredients/flour",
  "garlic": "ingredients/garlic",
  "garlic-powder": "ingredients/garlic",
  "gelatin": "ingredients/gelatin",
  "gin": "beverages/gin_and_tonic",
  "ginger": "ingredients/ginger",
  "gouda": "ingredients/gouda",
  "granola": "ingredients/baking_powder",
  "grapefruit": "ingredients/grapefruit",
  "grapes": "ingredients/grape",
  "green-beans": "ingredients/green_beans",
  "ground-beef": "ingredients/ground_beef",
  "guacamole": "ingredients/avocado",
  "ham": "ingredients/ham",
  "hazelnuts": "ingredients/hazelnuts",
  "honey": "ingredients/honey",
  "hot-chocolate": "beverages/hot_chocolate",
  "hot-dog": "ingredients/mustard",
  "hot-sauce": "ingredients/hot_sauce",
  "hotdog": "ingredients/mustard",
  "hummus": "ingredients/hummus",
  "iced-tea": "beverages/iced_tea",
  "icing-sugar": "ingredients/powdered_sugar",
  "jam": "ingredients/strawberry",
  "juice": "beverages/apple_juice",
  "kale": "ingredients/kale",
  "kefir": "ingredients/kefir",
  "ketchup": "ingredients/ketchup",
  "kiwi": "ingredients/kiwi",
  "lager": "ingredients/beer",
  "lamb": "ingredients/lamb",
  "lasagna": "ingredients/pasta",
  "lasagne": "ingredients/pasta",
  "leek": "ingredients/leek",
  "lemon": "ingredients/lemon",
  "lemonade": "beverages/lemonade",
  "lentils": "ingredients/lentils",
  "lettuce": "ingredients/lettuce",
  "lime": "ingredients/lime",
  "mackerel": "ingredients/mackerel",
  "mango": "ingredients/mango",
  "maple-syrup": "ingredients/maple_syrup",
  "marmalade": "ingredients/grapefruit",
  "marshmallows": "ingredients/brown_sugar",
  "mascarpone": "ingredients/mascarpone",
  "mayonnaise": "ingredients/mayonnaise",
  "meatballs": "ingredients/tempeh",
  "milk": "ingredients/milk",
  "milkshake": "beverages/milkshake",
  "mince": "ingredients/beef",
  "mineral-water": "ingredients/water",
  "mint": "ingredients/mint",
  "molasses": "ingredients/molasses",
  "mortadella": "ingredients/bacon",
  "mozzarella": "ingredients/mozzarella",
  "muesli": "ingredients/baking_powder",
  "mushroom": "ingredients/mushroom",
  "mussels": "ingredients/mussels",
  "mustard": "ingredients/mustard",
  "nachos": "ingredients/brie",
  "nuggets": "ingredients/chicken",
  "nutella": "ingredients/cocoa_powder",
  "nuts": "ingredients/walnuts",
  "oat-milk": "beverages/oat_milk",
  "oats": "ingredients/couscous",
  "olive-oil": "ingredients/olive_oil",
  "olives": "ingredients/olive_oil",
  "onion": "ingredients/onion",
  "onion-powder": "ingredients/onion_powder",
  "onions": "ingredients/onion",
  "orange": "ingredients/orange",
  "orange-juice": "beverages/orange_juice",
  "oregano": "ingredients/oregano",
  "oregano-dried": "ingredients/oregano",
  "pancetta": "ingredients/pancetta",
  "paprika": "ingredients/paprika",
  "parmesan": "ingredients/parmesan",
  "parsley": "ingredients/parsley",
  "pasta": "ingredients/pasta",
  "peach": "ingredients/peach",
  "peanut": "ingredients/peanuts",
  "peanut-butter": "ingredients/almonds",
  "peanuts": "ingredients/peanuts",
  "pear": "ingredients/pear",
  "peas": "ingredients/green_beans",
  "peppers": "ingredients/bell_pepper",
  "pesto": "ingredients/pesto",
  "pickles": "ingredients/pickles",
  "pineapple": "ingredients/pineapple",
  "pistachios": "ingredients/pistachios",
  "plum": "ingredients/plum",
  "pork": "ingredients/pork",
  "potato": "ingredients/potato",
  "potatoes": "ingredients/potato",
  "powdered-sugar": "ingredients/powdered_sugar",
  "prawns": "ingredients/prawns",
  "prosciutto": "ingredients/prosciutto",
  "prosecco": "beverages/prosecco",
  "pudding": "ingredients/gelatin",
  "pumpkin": "ingredients/pumpkin",
  "quinoa": "ingredients/quinoa",
  "raisins": "ingredients/blackberry",
  "raspberries": "ingredients/raspberry",
  "rice": "ingredients/rice",
  "rice-vinegar": "ingredients/rice_wine_vinegar",
  "ricotta": "ingredients/ricotta",
  "rosemary": "ingredients/rosemary",
  "rum": "beverages/whiskey",
  "salami": "ingredients/salami",
  "salmon": "ingredients/salmon",
  "salsa": "ingredients/ketchup",
  "salt": "ingredients/salt",
  "sardines": "ingredients/sardine",
  "sausage": "ingredients/sausage",
  "scallion": "ingredients/scallion",
  "seeds": "ingredients/sesame_seeds",
  "sesame-oil": "ingredients/sesame_oil",
  "shallot": "ingredients/leek",
  "shrimp": "ingredients/shrimp",
  "smoothie": "beverages/smoothie",
  "soda": "beverages/club_soda",
  "sour-cream": "ingredients/sour_cream",
  "soy-milk": "ingredients/soy_milk",
  "soy-sauce": "ingredients/soy_sauce",
  "spaghetti": "ingredients/pasta",
  "sparkling-water": "beverages/sparkling_water",
  "spinach": "ingredients/spinach",
  "spring-onion": "ingredients/scallion",
  "squid": "ingredients/squid",
  "sriracha": "ingredients/sriracha",
  "steak": "ingredients/beef",
  "stock": "ingredients/vegetable_stock",
  "strawberries": "ingredients/strawberry",
  "strawberry": "ingredients/strawberry",
  "sugar": "ingredients/sugar",
  "sweet-potato": "ingredients/sweet_potato",
  "sweetcorn": "ingredients/corn",
  "sweets": "ingredients/brown_sugar",
  "syrup": "ingredients/maple_syrup",
  "tahini": "ingredients/tahini",
  "tea": "ingredients/tea",
  "tempeh": "ingredients/tempeh",
  "thyme": "ingredients/thyme",
  "tofu": "ingredients/tofu",
  "tomato": "ingredients/tomato",
  "tomatoes": "ingredients/tomato",
  "trout": "ingredients/trout",
  "tuna": "ingredients/tuna",
  "turkey": "ingredients/turkey",
  "turmeric": "ingredients/turmeric",
  "vanilla": "ingredients/vanilla_extract",
  "veal": "ingredients/veal",
  "vegetable-oil": "ingredients/vegetable_oil",
  "vinegar": "ingredients/balsamic_vinegar",
  "vodka": "beverages/vodka_tonic",
  "walnuts": "ingredients/walnuts",
  "water": "ingredients/water",
  "watermelon": "ingredients/watermelon",
  "whiskey": "beverages/whiskey",
  "whisky": "beverages/whiskey",
  "wine": "beverages/wine",
  "worcestershire-sauce": "ingredients/balsamic_vinegar",
  "yeast": "ingredients/active_dry_yeast",
  "yogurt": "ingredients/yogurt",
  "zucchini": "ingredients/zucchini",
};

/**
 * Per-category outline icon, reusing an already-vendored asset, for when a
 * concept has no entry in `foodiconpackIndex` above. Keeps the fallback in
 * the same visual language instead of dropping to the emoji glyph. `other`
 * has no thematic food/drink icon to reuse — `FoodIcon` renders a neutral
 * lucide glyph for it instead of picking an arbitrary ingredient.
 */
export const foodiconpackCategoryFallback: Partial<Record<Category, string>> = {
  fruit: "ingredients/apple",
  vegetables: "ingredients/carrot",
  dairy: "ingredients/milk",
  "meat-fish": "ingredients/chicken",
  pantry: "ingredients/rice",
  "sauces-condiments": "ingredients/ketchup",
  "spices-herbs": "ingredients/basil",
  baking: "ingredients/flour",
  drinks: "ingredients/coffee",
  "breakfast-snacks": "ingredients/eggs",
  snacks: "ingredients/peanuts",
};
