import {
  Amphora,
  Apple,
  Banana,
  Bean,
  Beef,
  Beer,
  BottleWine,
  Box,
  Cake,
  CakeSlice,
  Candy,
  Carrot,
  Cherry,
  Citrus,
  Coffee,
  Cookie,
  CookingPot,
  Croissant,
  CupSoda,
  Cylinder,
  Donut,
  Droplets,
  Drumstick,
  Egg,
  Fish,
  Flame,
  GlassWater,
  Grape,
  Ham,
  IceCreamBowl,
  IceCreamCone,
  Leaf,
  Lollipop,
  Milk,
  Nut,
  Package,
  Pizza,
  Popcorn,
  Salad,
  Sandwich,
  Shell,
  Shrimp,
  Snowflake,
  Soup,
  Torus,
  Vegan,
  Wheat,
  Wine,
} from "lucide-react";
import type { LucideIcon } from "lucide-react";
import { categoryMeta } from "../lib/data";
import type { Category } from "../lib/types";

const iconMap: Record<string, LucideIcon> = {
  tomato: Cherry,
  onion: Amphora,
  garlic: Vegan,
  carrot: Carrot,
  potato: Bean,
  "bell-pepper": Vegan,
  spinach: Leaf,
  mushroom: Amphora,
  broccoli: Vegan,
  cauliflower: Vegan,
  lettuce: Salad,
  cucumber: Cylinder,
  zucchini: Cylinder,
  eggplant: Amphora,
  lemon: Citrus,
  lime: Citrus,
  avocado: Bean,
  apple: Apple,
  banana: Banana,
  orange: Citrus,
  berries: Grape,
  celery: Leaf,
  peas: Bean,
  ginger: Bean,
  chili: Flame,
  parsley: Leaf,
  cilantro: Leaf,
  basil: Leaf,
  thyme: Leaf,
  oregano: Leaf,
  rosemary: Leaf,
  mint: Leaf,
  "oregano-dried": Leaf,
  milk: Milk,
  butter: Box,
  eggs: Egg,
  yogurt: IceCreamBowl,
  cream: Milk,
  cheese: CakeSlice,
  mozzarella: Torus,
  parmesan: CakeSlice,
  feta: Box,
  chicken: Drumstick,
  beef: Beef,
  pork: Ham,
  bacon: Ham,
  ham: Ham,
  sausage: Drumstick,
  fish: Fish,
  salmon: Fish,
  shrimp: Shrimp,
  tuna: Fish,
  pasta: Wheat,
  rice: Wheat,
  noodles: Soup,
  bread: Sandwich,
  tortilla: Torus,
  chickpeas: Bean,
  lentils: Bean,
  beans: Bean,
  "coconut-milk": Milk,
  "canned-tomatoes": Cylinder,
  olives: Shell,
  oats: Wheat,
  cereal: Popcorn,
  nuts: Nut,
  "olive-oil": BottleWine,
  "vegetable-oil": BottleWine,
  "soy-sauce": BottleWine,
  vinegar: BottleWine,
  "balsamic-vinegar": BottleWine,
  "tomato-sauce": Soup,
  "tomato-paste": Cylinder,
  pesto: Leaf,
  mustard: Droplets,
  ketchup: Droplets,
  mayonnaise: Droplets,
  honey: Droplets,
  jam: Amphora,
  "peanut-butter": Amphora,
  "sesame-oil": BottleWine,
  "fish-sauce": BottleWine,
  "rice-vinegar": BottleWine,
  stock: CookingPot,
  salsa: Amphora,
  salt: Cylinder,
  "black-pepper": Cylinder,
  cumin: Cylinder,
  paprika: Flame,
  "curry-powder": Flame,
  turmeric: Cylinder,
  cinnamon: Cylinder,
  "chili-flakes": Flame,
  "garlic-powder": Cylinder,
  "onion-powder": Cylinder,
  "bay-leaf": Leaf,
  flour: Wheat,
  sugar: Candy,
  "brown-sugar": Candy,
  "baking-powder": Cylinder,
  "baking-soda": Cylinder,
  vanilla: Droplets,
  chocolate: Cookie,
  yeast: Croissant,
  water: GlassWater,
  juice: CupSoda,
  coffee: Coffee,
  tea: Coffee,
  wine: Wine,
  beer: Beer,
  soda: CupSoda,
  "ice-cream": IceCreamCone,
  "chocolate-bar": Cookie,
  "chocolate-spread": Cookie,
  biscuits: Cookie,
  sweets: Candy,
  crisps: Popcorn,
  crackers: Cookie,
  popcorn: Popcorn,
  pretzels: Croissant,
  pizza: Pizza,
  ice: Snowflake,

  // ── Extended aliases ──────────────────────────────────────────────────────
  // Free-typed items get an icon key that is a slug of the text entered (see
  // ai.ts), and the concept catalog's aliases are English-only, so common
  // plurals, synonyms and Italian names need their own row or they fall back
  // to the plain category box. Icons are reused from the imports above.

  // plurals / spelling variants
  tomatoes: Cherry,
  onions: Amphora,
  potatoes: Bean,
  carrots: Carrot,
  lemons: Citrus,
  apples: Apple,
  oranges: Citrus,
  aubergine: Amphora,
  courgette: Cylinder,
  peppers: Vegan,
  "spring-onion": Leaf,
  scallion: Leaf,
  shallot: Amphora,
  cookie: Cookie,
  cookies: Cookie,
  biscuit: Cookie,

  // fruit
  strawberry: Grape,
  strawberries: Grape,
  blueberries: Grape,
  raspberries: Grape,
  blackberries: Grape,
  grapes: Grape,
  cherries: Cherry,
  mango: Apple,
  pineapple: Apple,
  peach: Apple,
  pear: Apple,
  plum: Apple,
  kiwi: Apple,
  melon: Apple,
  watermelon: Apple,
  grapefruit: Citrus,
  coconut: Nut,
  dates: Bean,
  raisins: Grape,

  // veg
  corn: Wheat,
  sweetcorn: Wheat,
  cabbage: Salad,
  kale: Leaf,
  leek: Leaf,
  pumpkin: Amphora,
  "sweet-potato": Bean,
  asparagus: Leaf,
  "green-beans": Bean,
  artichoke: Vegan,
  pickles: Amphora,
  capers: Bean,

  // nuts & seeds
  almonds: Nut,
  walnuts: Nut,
  cashews: Nut,
  peanut: Nut,
  peanuts: Nut,
  pistachios: Nut,
  hazelnuts: Nut,
  seeds: Nut,

  // grains, pasta & bakery
  quinoa: Wheat,
  couscous: Wheat,
  spaghetti: Wheat,
  lasagne: Wheat,
  lasagna: Wheat,
  gnocchi: Wheat,
  ravioli: Wheat,
  tortellini: Wheat,
  breadcrumbs: Wheat,
  baguette: Sandwich,
  croissant: Croissant,
  brioche: Croissant,
  bun: Sandwich,
  roll: Sandwich,
  pita: Torus,
  bagel: Torus,
  muffin: Cake,
  pancakes: CakeSlice,
  waffles: CakeSlice,
  granola: Popcorn,
  muesli: Popcorn,

  // sweets & desserts
  cake: Cake,
  cupcake: Cake,
  brownie: Cookie,
  pie: CakeSlice,
  tart: CakeSlice,
  donut: Donut,
  doughnut: Donut,
  lollipop: Lollipop,
  marshmallows: Candy,
  nutella: Cookie,
  pudding: IceCreamBowl,

  // snacks & fast food
  chips: Popcorn,
  fries: Popcorn,
  nachos: Popcorn,
  burger: Sandwich,
  hamburger: Sandwich,
  hotdog: Sandwich,
  "hot-dog": Sandwich,
  taco: Torus,
  burrito: Torus,
  sushi: Fish,
  nuggets: Drumstick,

  // proteins
  turkey: Drumstick,
  lamb: Beef,
  duck: Drumstick,
  veal: Beef,
  mince: Beef,
  "ground-beef": Beef,
  meatballs: Beef,
  steak: Beef,
  salami: Ham,
  prosciutto: Ham,
  pepperoni: Ham,
  pancetta: Ham,
  mortadella: Ham,
  anchovies: Fish,
  cod: Fish,
  sardines: Fish,
  mackerel: Fish,
  trout: Fish,
  crab: Shell,
  mussels: Shell,
  clams: Shell,
  squid: Shell,
  prawns: Shrimp,
  tofu: Box,
  tempeh: Box,

  // dairy & eggs
  ricotta: IceCreamBowl,
  mascarpone: IceCreamBowl,
  "cottage-cheese": IceCreamBowl,
  cheddar: CakeSlice,
  gouda: CakeSlice,
  brie: CakeSlice,
  "cream-cheese": Box,
  "sour-cream": Milk,
  "oat-milk": Milk,
  "almond-milk": Milk,
  "soy-milk": Milk,
  kefir: Milk,

  // condiments & pantry
  hummus: Amphora,
  guacamole: Bean,
  tahini: Amphora,
  passata: Soup,
  "maple-syrup": Droplets,
  syrup: Droplets,
  molasses: Droplets,
  marmalade: Amphora,
  "hot-sauce": BottleWine,
  sriracha: BottleWine,
  "worcestershire-sauce": BottleWine,
  broth: CookingPot,
  bouillon: CookingPot,
  cocoa: Cylinder,
  "cocoa-powder": Cylinder,
  "icing-sugar": Candy,
  "powdered-sugar": Candy,
  sprinkles: Candy,
  gelatin: Cylinder,

  // drinks
  "sparkling-water": GlassWater,
  "mineral-water": GlassWater,
  "orange-juice": CupSoda,
  "apple-juice": CupSoda,
  lemonade: CupSoda,
  cola: CupSoda,
  "energy-drink": CupSoda,
  smoothie: CupSoda,
  milkshake: CupSoda,
  "iced-tea": CupSoda,
  espresso: Coffee,
  cappuccino: Coffee,
  "hot-chocolate": Coffee,
  cider: Beer,
  lager: Beer,
  prosecco: Wine,
  champagne: Wine,
  whiskey: BottleWine,
  whisky: BottleWine,
  vodka: BottleWine,
  gin: BottleWine,
  rum: BottleWine,

  // Italian names (catalog aliases are English-only)
  biscotti: Cookie,
  biscotto: Cookie,
  torta: Cake,
  gelato: IceCreamCone,
  caramelle: Candy,
  cioccolato: Cookie,
  pane: Sandwich,
  panino: Sandwich,
  riso: Wheat,
  farina: Wheat,
  zucchero: Candy,
  sale: Cylinder,
  pepe: Cylinder,
  olio: BottleWine,
  aceto: BottleWine,
  latte: Milk,
  formaggio: CakeSlice,
  uova: Egg,
  uovo: Egg,
  burro: Box,
  pollo: Drumstick,
  manzo: Beef,
  maiale: Ham,
  pesce: Fish,
  gamberi: Shrimp,
  mela: Apple,
  mele: Apple,
  limone: Citrus,
  arancia: Citrus,
  pomodoro: Cherry,
  pomodori: Cherry,
  cipolla: Amphora,
  aglio: Vegan,
  carota: Carrot,
  patata: Bean,
  patate: Bean,
  insalata: Salad,
  vino: Wine,
  birra: Beer,
  acqua: GlassWater,
  caffe: Coffee,
  the: Coffee,

  fruit: Cherry,
  vegetables: Carrot,
  dairy: Milk,
  "meat-fish": Beef,
  pantry: Package,
  "sauces-condiments": Droplets,
  "spices-herbs": Leaf,
  baking: Wheat,
  drinks: GlassWater,
  "breakfast-snacks": Cookie,
  snacks: Popcorn,
  other: Package,
  dessert: Donut,
};

export function FoodIcon({
  iconKey,
  category,
  size = 40,
  variant = "chip",
}: {
  iconKey: string;
  category: Category;
  size?: number;
  variant?: "chip" | "bare";
}) {
  const meta = categoryMeta[category];
  const Icon = iconMap[iconKey] ?? iconMap[category] ?? Package;

  if (variant === "bare") {
    return <Icon size={size} strokeWidth={1.75} color={meta.color} />;
  }

  return (
    <span
      style={{
        display: "inline-flex",
        width: size,
        height: size,
        borderRadius: Math.round(size * 0.28),
        alignItems: "center",
        justifyContent: "center",
        backgroundColor: meta.bg,
        flexShrink: 0,
      }}
    >
      <Icon size={Math.round(size * 0.5)} strokeWidth={2} color={meta.color} />
    </span>
  );
}
