import { categoryMeta } from "../lib/data";
import type { Category } from "../lib/types";

/**
 * Emoji glyph for a food, keyed by the same `iconKey` slugs used across the app
 * (concept ids, their common plurals / synonyms, and Italian names — see
 * `ai.ts` and the concept catalog). Anything not listed falls back to the
 * category emoji, then a shopping trolley.
 */
const foodEmoji: Record<string, string> = {
  // ── Fruit ────────────────────────────────────────────────────────────────
  lemon: "🍋",
  lime: "🍋",
  avocado: "🥑",
  apple: "🍎",
  banana: "🍌",
  orange: "🍊",
  berries: "🫐",
  strawberry: "🍓",
  strawberries: "🍓",
  blueberries: "🫐",
  raspberries: "🍇",
  blackberries: "🍇",
  grapes: "🍇",
  raisins: "🍇",
  cherries: "🍒",
  mango: "🥭",
  pineapple: "🍍",
  peach: "🍑",
  pear: "🍐",
  plum: "🫐",
  kiwi: "🥝",
  melon: "🍈",
  watermelon: "🍉",
  grapefruit: "🍊",
  coconut: "🥥",
  dates: "🌴",

  // ── Vegetables ───────────────────────────────────────────────────────────
  tomato: "🍅",
  tomatoes: "🍅",
  onion: "🧅",
  onions: "🧅",
  "spring-onion": "🧅",
  scallion: "🧅",
  shallot: "🧅",
  leek: "🧅",
  garlic: "🧄",
  carrot: "🥕",
  carrots: "🥕",
  potato: "🥔",
  potatoes: "🥔",
  "sweet-potato": "🍠",
  "bell-pepper": "🫑",
  peppers: "🫑",
  spinach: "🥬",
  lettuce: "🥬",
  cabbage: "🥬",
  kale: "🥬",
  celery: "🥬",
  asparagus: "🥬",
  mushroom: "🍄",
  broccoli: "🥦",
  cauliflower: "🥦",
  cucumber: "🥒",
  pickles: "🥒",
  zucchini: "🥒",
  courgette: "🥒",
  eggplant: "🍆",
  aubergine: "🍆",
  peas: "🫛",
  "green-beans": "🫛",
  ginger: "🫚",
  chili: "🌶️",
  corn: "🌽",
  sweetcorn: "🌽",
  pumpkin: "🎃",
  artichoke: "🌿",
  capers: "🫒",

  // ── Herbs & spices ───────────────────────────────────────────────────────
  parsley: "🌿",
  cilantro: "🌿",
  basil: "🌿",
  thyme: "🌿",
  oregano: "🌿",
  "oregano-dried": "🌿",
  rosemary: "🌿",
  mint: "🌿",
  "bay-leaf": "🌿",
  pesto: "🌿",
  salt: "🧂",
  "black-pepper": "🧂",
  cumin: "🌰",
  paprika: "🌶️",
  "curry-powder": "🍛",
  turmeric: "🟡",
  cinnamon: "🪵",
  "chili-flakes": "🌶️",
  "garlic-powder": "🧄",
  "onion-powder": "🧅",

  // ── Nuts & seeds ─────────────────────────────────────────────────────────
  nuts: "🥜",
  peanut: "🥜",
  peanuts: "🥜",
  almonds: "🥜",
  walnuts: "🥜",
  cashews: "🥜",
  pistachios: "🥜",
  hazelnuts: "🥜",
  seeds: "🌰",

  // ── Dairy & eggs ─────────────────────────────────────────────────────────
  milk: "🥛",
  "oat-milk": "🥛",
  "almond-milk": "🥛",
  "soy-milk": "🥛",
  kefir: "🥛",
  cream: "🥛",
  "sour-cream": "🥛",
  yogurt: "🥛",
  butter: "🧈",
  eggs: "🥚",
  cheese: "🧀",
  "cream-cheese": "🧀",
  mozzarella: "🧀",
  parmesan: "🧀",
  feta: "🧀",
  ricotta: "🧀",
  mascarpone: "🧀",
  "cottage-cheese": "🧀",
  cheddar: "🧀",
  gouda: "🧀",
  brie: "🧀",
  "cream-cheese": "🧀",

  // ── Meat & fish ──────────────────────────────────────────────────────────
  chicken: "🍗",
  turkey: "🦃",
  duck: "🦆",
  nuggets: "🍗",
  beef: "🥩",
  veal: "🥩",
  lamb: "🥩",
  steak: "🥩",
  mince: "🥩",
  "ground-beef": "🥩",
  meatballs: "🧆",
  pork: "🥓",
  bacon: "🥓",
  pancetta: "🥓",
  ham: "🍖",
  sausage: "🌭",
  salami: "🥓",
  prosciutto: "🥓",
  pepperoni: "🍕",
  mortadella: "🥓",
  fish: "🐟",
  salmon: "🐟",
  tuna: "🐟",
  anchovies: "🐟",
  cod: "🐟",
  sardines: "🐟",
  mackerel: "🐟",
  trout: "🐟",
  shrimp: "🦐",
  prawns: "🦐",
  crab: "🦀",
  mussels: "🦪",
  clams: "🦪",
  squid: "🦑",
  tofu: "🧆",
  tempeh: "🧆",

  // ── Grains, pasta & bakery ───────────────────────────────────────────────
  pasta: "🍝",
  spaghetti: "🍝",
  ravioli: "🥟",
  tortellini: "🥟",
  tortelloni: "🥟",
  lasagne: "🍝",
  lasagna: "🍝",
  noodles: "🍜",
  gnocchi: "🥟",
  ravioli: "🥟",
  tortellini: "🥟",
  rice: "🍚",
  quinoa: "🌾",
  couscous: "🌾",
  oats: "🌾",
  granola: "🥣",
  muesli: "🥣",
  cereal: "🥣",
  flour: "🌾",
  bread: "🍞",
  breadcrumbs: "🍞",
  baguette: "🥖",
  pita: "🫓",
  pitta: "🫓",
  roll: "🥖",
  croissant: "🥐",
  brioche: "🥐",
  bun: "🥯",
  bagel: "🥯",
  pita: "🫓",
  tortilla: "🫓",
  muffin: "🧁",
  pancakes: "🥞",
  waffles: "🧇",

  // ── Legumes & tinned ─────────────────────────────────────────────────────
  beans: "🫘",
  chickpeas: "🫘",
  lentils: "🫘",
  hummus: "🫘",
  tahini: "🫘",
  "canned-tomatoes": "🥫",
  "tomato-paste": "🥫",
  "tomato-sauce": "🥫",
  passata: "🥫",
  "coconut-milk": "🥥",
  olives: "🫒",
  guacamole: "🥑",

  // ── Oils, sauces & condiments ────────────────────────────────────────────
  "olive-oil": "🫒",
  "vegetable-oil": "🫗",
  "sesame-oil": "🫗",
  "soy-sauce": "🍶",
  "fish-sauce": "🐟",
  vinegar: "🍶",
  "balsamic-vinegar": "🍶",
  "rice-vinegar": "🍶",
  "worcestershire-sauce": "🍶",
  mustard: "🌭",
  ketchup: "🍅",
  mayonnaise: "🥚",
  salsa: "🍅",
  "hot-sauce": "🌶️",
  sriracha: "🌶️",
  honey: "🍯",
  syrup: "🍯",
  "maple-syrup": "🍁",
  molasses: "🍯",
  jam: "🍓",
  marmalade: "🍊",
  "peanut-butter": "🥜",
  stock: "🍲",
  broth: "🍲",
  bouillon: "🍲",

  // ── Baking ───────────────────────────────────────────────────────────────
  sugar: "🍬",
  "brown-sugar": "🍬",
  "icing-sugar": "🍬",
  "powdered-sugar": "🍬",
  "baking-powder": "🥣",
  "baking-soda": "🥣",
  yeast: "🍞",
  vanilla: "🍦",
  cocoa: "🍫",
  "cocoa-powder": "🍫",
  chocolate: "🍫",
  sprinkles: "🍩",
  gelatin: "🍮",

  // ── Drinks ───────────────────────────────────────────────────────────────
  water: "💧",
  "sparkling-water": "💧",
  "mineral-water": "💧",
  juice: "🧃",
  "orange-juice": "🧃",
  "apple-juice": "🧃",
  lemonade: "🍋",
  coffee: "☕",
  espresso: "☕",
  cappuccino: "☕",
  "hot-chocolate": "☕",
  tea: "🍵",
  chamomile: "🌼",
  camomilla: "🌼",
  "iced-tea": "🧋",
  soda: "🥤",
  cola: "🥤",
  "energy-drink": "🥤",
  smoothie: "🥤",
  milkshake: "🥤",
  wine: "🍷",
  prosecco: "🍾",
  champagne: "🍾",
  beer: "🍺",
  cider: "🍺",
  lager: "🍺",
  whiskey: "🥃",
  whisky: "🥃",
  rum: "🥃",
  vodka: "🍸",
  gin: "🍸",

  // ── Sweets, snacks & fast food ───────────────────────────────────────────
  "ice-cream": "🍦",
  gelato: "🍨",
  pudding: "🍮",
  "chocolate-bar": "🍫",
  "chocolate-spread": "🍫",
  nutella: "🍫",
  biscuits: "🍪",
  biscuit: "🍪",
  cookie: "🍪",
  cookies: "🍪",
  brownie: "🍫",
  sweets: "🍬",
  marshmallows: "🍬",
  lollipop: "🍭",
  cake: "🍰",
  cupcake: "🧁",
  pie: "🥧",
  tart: "🥧",
  donut: "🍩",
  doughnut: "🍩",
  crisps: "🍟",
  chips: "🍟",
  fries: "🍟",
  crackers: "🍘",
  popcorn: "🍿",
  pretzels: "🥨",
  nachos: "🧀",
  pizza: "🍕",
  burger: "🍔",
  hamburger: "🍔",
  hotdog: "🌭",
  "hot-dog": "🌭",
  taco: "🌮",
  burrito: "🌯",
  sushi: "🍣",
  ice: "🧊",

  // ── Italian names (catalog aliases are English-only) ─────────────────────
  biscotti: "🍪",
  biscotto: "🍪",
  torta: "🍰",
  caramelle: "🍬",
  cioccolato: "🍫",
  pane: "🍞",
  panino: "🥪",
  riso: "🍚",
  farina: "🌾",
  zucchero: "🍬",
  sale: "🧂",
  pepe: "🧂",
  olio: "🫒",
  aceto: "🍶",
  latte: "🥛",
  formaggio: "🧀",
  uova: "🥚",
  uovo: "🥚",
  burro: "🧈",
  pollo: "🍗",
  manzo: "🥩",
  maiale: "🥓",
  pesce: "🐟",
  gamberi: "🦐",
  mela: "🍎",
  mele: "🍎",
  limone: "🍋",
  arancia: "🍊",
  pomodoro: "🍅",
  pomodori: "🍅",
  cipolla: "🧅",
  aglio: "🧄",
  carota: "🥕",
  patata: "🥔",
  patate: "🥔",
  insalata: "🥗",
  vino: "🍷",
  birra: "🍺",
  acqua: "💧",
  caffe: "☕",
  the: "🍵",
};

const categoryEmoji: Record<Category, string> = {
  fruit: "🍎",
  vegetables: "🥕",
  dairy: "🥛",
  "meat-fish": "🍖",
  pantry: "🥫",
  "sauces-condiments": "🫙",
  "spices-herbs": "🌿",
  baking: "🧁",
  drinks: "🥤",
  "breakfast-snacks": "🥐",
  snacks: "🍿",
  other: "🛒",
};

export function FoodIcon({
  iconKey,
  category,
  size = 40,
  variant = "chip",
}: {
  iconKey: string;
  category: Category;
  size?: number;
  variant?: "chip" | "bare";
}) {
  const meta = categoryMeta[category];
  const emoji = foodEmoji[iconKey] ?? categoryEmoji[category] ?? "🛒";

  if (variant === "bare") {
    return (
      <span
        aria-hidden
        style={{ fontSize: Math.round(size * 0.9), lineHeight: 1, display: "inline-block" }}
      >
        {emoji}
      </span>
    );
  }

  return (
    <span
      aria-hidden
      style={{
        display: "inline-flex",
        width: size,
        height: size,
        borderRadius: Math.round(size * 0.28),
        alignItems: "center",
        justifyContent: "center",
        backgroundColor: meta.bg,
        fontSize: Math.round(size * 0.56),
        lineHeight: 1,
        flexShrink: 0,
      }}
    >
      {emoji}
    </span>
  );
}
