import React from "react";
import { View } from "react-native";
import {
  Amphora,
  Apple,
  Banana,
  Bean,
  Beef,
  BottleWine,
  Box,
  CakeSlice,
  Candy,
  Carrot,
  Cherry,
  Citrus,
  Coffee,
  Cookie,
  CookingPot,
  Croissant,
  CupSoda,
  Cylinder,
  Donut,
  Droplets,
  Drumstick,
  Egg,
  Fish,
  Flame,
  GlassWater,
  Grape,
  Ham,
  IceCreamBowl,
  IceCreamCone,
  Leaf,
  Milk,
  Nut,
  Package,
  Pizza,
  Popcorn,
  Salad,
  Sandwich,
  Shell,
  Shrimp,
  Snowflake,
  Soup,
  Torus,
  Vegan,
  Wheat,
  Wine,
} from "lucide-react-native";
import type { LucideIcon } from "lucide-react-native";
import { categoryMeta } from "../lib/data";
import type { Category } from "../lib/types";

const iconMap: Record<string, LucideIcon> = {
  tomato: Cherry,
  onion: Amphora,
  garlic: Vegan,
  carrot: Carrot,
  potato: Bean,
  "bell-pepper": Vegan,
  spinach: Leaf,
  mushroom: Amphora,
  broccoli: Vegan,
  cauliflower: Vegan,
  lettuce: Salad,
  cucumber: Cylinder,
  zucchini: Cylinder,
  eggplant: Amphora,
  lemon: Citrus,
  lime: Citrus,
  avocado: Bean,
  apple: Apple,
  banana: Banana,
  orange: Citrus,
  berries: Grape,
  celery: Leaf,
  peas: Bean,
  ginger: Bean,
  chili: Flame,
  parsley: Leaf,
  cilantro: Leaf,
  basil: Leaf,
  thyme: Leaf,
  oregano: Leaf,
  rosemary: Leaf,
  mint: Leaf,
  "oregano-dried": Leaf,
  milk: Milk,
  butter: Box,
  eggs: Egg,
  yogurt: IceCreamBowl,
  cream: Milk,
  cheese: CakeSlice,
  mozzarella: Torus,
  parmesan: CakeSlice,
  feta: Box,
  chicken: Drumstick,
  beef: Beef,
  pork: Ham,
  bacon: Ham,
  ham: Ham,
  sausage: Drumstick,
  fish: Fish,
  salmon: Fish,
  shrimp: Shrimp,
  tuna: Fish,
  pasta: Wheat,
  rice: Wheat,
  noodles: Soup,
  bread: Sandwich,
  tortilla: Torus,
  chickpeas: Bean,
  lentils: Bean,
  beans: Bean,
  "coconut-milk": Milk,
  "canned-tomatoes": Cylinder,
  olives: Shell,
  oats: Wheat,
  cereal: Popcorn,
  nuts: Nut,
  "olive-oil": BottleWine,
  "vegetable-oil": BottleWine,
  "soy-sauce": BottleWine,
  vinegar: BottleWine,
  "balsamic-vinegar": BottleWine,
  "tomato-sauce": Soup,
  "tomato-paste": Cylinder,
  pesto: Leaf,
  mustard: Droplets,
  ketchup: Droplets,
  mayonnaise: Droplets,
  honey: Droplets,
  jam: Amphora,
  "peanut-butter": Amphora,
  "sesame-oil": BottleWine,
  "fish-sauce": BottleWine,
  "rice-vinegar": BottleWine,
  stock: CookingPot,
  salsa: Amphora,
  salt: Cylinder,
  "black-pepper": Cylinder,
  cumin: Cylinder,
  paprika: Flame,
  "curry-powder": Flame,
  turmeric: Cylinder,
  cinnamon: Cylinder,
  "chili-flakes": Flame,
  "garlic-powder": Cylinder,
  "onion-powder": Cylinder,
  "bay-leaf": Leaf,
  flour: Wheat,
  sugar: Candy,
  "brown-sugar": Candy,
  "baking-powder": Cylinder,
  "baking-soda": Cylinder,
  vanilla: Droplets,
  chocolate: Cookie,
  yeast: Croissant,
  water: GlassWater,
  juice: CupSoda,
  coffee: Coffee,
  tea: Coffee,
  wine: Wine,
  beer: GlassWater,
  soda: CupSoda,
  "ice-cream": IceCreamCone,
  "frozen-vegetables": Snowflake,
  "frozen-berries": Snowflake,
  pizza: Pizza,
  "frozen-meat": Snowflake,
  "frozen-fish": Snowflake,
  ice: Snowflake,
  produce: Salad,
  dairy: Milk,
  "meat-fish": Beef,
  pantry: Package,
  "sauces-condiments": Droplets,
  "spices-herbs": Leaf,
  baking: Wheat,
  drinks: GlassWater,
  frozen: Snowflake,
  other: Package,
  dessert: Donut,
};

export function FoodIcon({
  iconKey,
  category,
  size = 40,
  variant = "chip",
}: {
  iconKey: string;
  category: Category;
  size?: number;
  variant?: "chip" | "bare";
}) {
  const meta = categoryMeta[category];
  const Icon = iconMap[iconKey] ?? iconMap[category] ?? Package;

  if (variant === "bare") {
    return <Icon size={size} strokeWidth={1.75} color={meta.color} />;
  }

  return (
    <View
      style={{
        width: size,
        height: size,
        borderRadius: Math.round(size * 0.28),
        alignItems: "center",
        justifyContent: "center",
        backgroundColor: meta.bg,
      }}
    >
      <Icon size={Math.round(size * 0.5)} strokeWidth={2} color={meta.color} />
    </View>
  );
}
